### PR TITLE
fix(core): enhancement AnomalyDetector and LoadRetriever

### LINKED ISSUE #989: [Discuss] Error interrupt LoadRetriever loop
Hi, AutoMQ community, an `Error` will causes the loop to exit, maybe need catch it let the task continue or provide metrics for task state.

Detail see, https://github.com/AutoMQ/automq/blob/baf30f069c58bdb7c88bf9a246cbd45630ea9793/core/src/main/java/kafka/autobalancer/LoadRetriever.java#L431-L435

### PR DESCRIPTION
**Pull request by Wzy19930507**
close #989

* Enhancement AnomalyDetector log throwable and exit loop.
* Enhancement LoadRetriever log throwable and exit loop.

### CODE REVIEW

File: core/src/main/java/kafka/autobalancer/LoadRetriever.java [hunk 1]
```diff
@@ -428,8 +428,8 @@ public void retrieve() {
                 createTopic();
                 this.mainExecutorService.schedule(this::retrieve, 1, TimeUnit.SECONDS);
                 return;
-            } catch (Exception e) {
```
Comment (SCNieh) [inline core/src/main/java/kafka/autobalancer/LoadRetriever.java:431]: We rerun the task on `Exception` is because `Exception` is expected to be recoverable, however for non-recoverable cases (like most of the `Error`), schedule another task is unneccessary becasue the current JVM status is unpredictable, so maybe just add catch `Throwable` after `Exception`, and logging it properly

File: core/src/main/java/kafka/autobalancer/LoadRetriever.java [hunk 2]
```diff
@@ -428,8 +428,8 @@ public void retrieve() {
...
-                logger.error("Consumer poll error", e);
+            } catch (Throwable throwable) {
```
Comment (SCNieh) [inline core/src/main/java/kafka/autobalancer/LoadRetriever.java:431]: We rerun the task on `Exception` is because `Exception` is expected to be recoverable, however for non-recoverable cases (like most of the `Error`), schedule another task is unneccessary becasue the current JVM status is unpredictable, so maybe just add catch `Throwable` after `Exception`, and logging it properly

File: core/src/main/java/kafka/autobalancer/LoadRetriever.java [hunk 3]
```diff
@@ -428,8 +428,8 @@ public void retrieve() {
...
+                logger.error("Consumer poll throwable", throwable);
```
Comment (SCNieh) [inline core/src/main/java/kafka/autobalancer/LoadRetriever.java:432]: there is no need to change the logging text here, as "throwable" is an adj.

**Review by SCNieh — APPROVED** [review]
