### PR TITLE
fix(metadataimage): fix getObjects not complete cf when throw exception

### LINKED ISSUE #1729: [BUG] metaStream replay forever hang.
### Version & Environment

commit ed986c9c9298b1cb

### What went wrong?

trigger failover very often.

after one day or some time. the partition failover can't success.

### How to reproduce the issue?

trigger failover very often.
A to B, B to C, C to A

### PR DESCRIPTION
**Pull request by lifepuzzlefun**
fix #1729

### CODE REVIEW

File: metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java [hunk 1]
```diff
@@ -197,104 +198,113 @@ void fillObjects(
...
+                        if (ex != null) {
+                            index = 0;
+                        }
+                        // load stream set object index
+                        int finalIndex = index;
+                        loadStreamSetObjectInfo(ctx, finalStreamSetObjects, index).thenAccept(v -> {
+                            ctx.nextStartOffset = finalNextStartOffset;
+                            fillObjects(ctx, stream, objects, finalLastRangeIndex, finalStreamObjectIndex, streamObjects,
+                                finalIndex, finalStreamSetObjects, finalNode);
+                        }).exceptionally(e -> {
```
Comment (lifepuzzlefun) [inline metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java:262]: add exception handle for thenAccept returned exception cf

File: metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java [hunk 2]
```diff
@@ -197,104 +198,113 @@ void fillObjects(
...
                 }
             }
-            // case 1. streamSetObjectIndex >= streamSetObjects.size(), which means we have reached the end of the stream set objects.
-            // case 2. objects.size() == roundStartObjectSize, which means we have not found any new object in this round.
-            if (streamSetObjectIndex >= streamSetObjects.size() || objects.size() == roundStartObjectSize) {
-                // move to the next range
-                // This can ensure that we can break the loop.
-                streamSetObjects = null;
-            }
+        } catch (Throwable e) {
```
Comment (lifepuzzlefun) [inline metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java:305]: add try catch block log and rethrow.

File: metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java [hunk 3]
```diff
@@ -626,7 +636,7 @@ static class GetObjectsContext {
         LocalStreamRangeIndexCache indexCache;
 
         CompletableFuture<InRangeObjects> cf = new CompletableFuture<>();
-        Map<Long, Optional<StreamOffsetRange>> object2range = new HashMap<>();
+        Map<Long, StreamOffsetRange> object2range = new ConcurrentHashMap<>();
```
Comment (lifepuzzlefun) [inline metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java:639]: change to ConcurrentHashMap to protect multi-thread access.
although the current objectStorage read-callback-thread is single-thread.

File: metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java [hunk 4]
```diff
@@ -445,7 +455,7 @@ private CompletableFuture<Void> loadStreamSetObjectInfo(GetObjectsContext ctx,
 
     private Optional<StreamOffsetRange> findStreamInStreamSetObject(GetObjectsContext ctx, S3StreamSetObject object) {
         if (object.ranges().length == 0) {
-            return ctx.object2range.get(object.objectId());
+            return Optional.ofNullable(ctx.object2range.get(object.objectId()));
```
Comment (lifepuzzlefun) [inline metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java:458]: ctx.object2range.get may return null.

File: metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java (hunk 3 above)
Comment (superhx) [inline metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java:639]: object2range should keep the Map<Long, Optional<StreamOffsetRange>>, cause of we need to known whether the object contains the stream

File: metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java [hunk 5]
```diff
@@ -197,104 +198,113 @@ void fillObjects(
...
-                    //noinspection StatementWithEmptyBody
-                    if (objects.isEmpty() && streamObject.startOffset() <= nextStartOffset && streamObject.endOffset() > nextStartOffset) {
-                        // it's the first object, we only need the stream object contains the nextStartOffset
-                    } else if (streamObject.endOffset() <= nextStartOffset) {
-                        // the stream object not match the requirement, move to the next stream object
-                        continue;
-                    } else {
-                        // the streamObject.startOffset() > nextStartOffset
-                        break;
+        try {
```
Comment (superhx) [inline metadata/src/main/java/org/apache/kafka/image/S3StreamsMetadataImage.java:201]: Could you add a new method fillObjects0 to avoid to too much change.

**Comment by lifepuzzlefun** [comment]
wait for find out why the npe throw when loadsso infor.

**Comment by lifepuzzlefun** [comment]
why sso npe the access log for object2range show the object is loaded but the setter call from different thread. make map thread safe the problem fix.

**Comment by lifepuzzlefun** [comment]
map get time: 
14270962722734924 time get 7576901

start load object cf time: 
14270962055302105=7576901=7576901=973

map put time: 
14270962084979177=7576901=GetRangeFinishContext{callNumber=1182, timeNano=14270962084979132, objectId=7576901, range=Optional.empty,
threadName='s3-read-cb-executor-1', jindex=2677},


the map access thread maybe from 

14255621939630669=5817238=GetRangeFinishContext{callNumber=409, timeNano=14255621939630604, objectId=5817238, range=Optional.empty, threadName='stream-reader-5', jindex=529},
14255629523695857=6401306=GetRangeFinishContext{callNumber=409, timeNano=14255629523695823, objectId=6401306, range=Optional.empty, threadName='stream-reader-5', jindex=3283},
14255626754772881=6020939=GetRangeFinishContext{callNumber=409, timeNano=14255626754772830, objectId=6020939, range=Optional.empty, threadName='s3-read-cb-executor-1', jindex=1732},
14255627476509278=6035895=GetRangeFinishContext{callNumber=409, timeNano=14255627476509238, objectId=6035895, range=Optional.empty, threadName='stream-reader-5', jindex=1842},
14255629522004362=6274076=GetRangeFinishContext{callNumber=409, timeNano=14255629522004341, objectId=6274076, range=Optional.empty, threadName='stream-reader-5', jindex=2955},
14255626622975906=6018913=GetRangeFinishContext{callNumber=409, timeNano=14255626622975866, objectId=6018913, range=Optional.empty, threadName='s3-read-cb-executor-1', jindex=1712},

**Review by superhx — APPROVED** [review]
